//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\Administrator\Desktop\vs\menu_block\MainMenu.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: Administrator
//              Version: NX 8.5
//              Date: 04-21-2016  (Format: mm-dd-yyyy)
//              Time: 11:23
//
//==============================================================================

#ifndef MAINMENU_H_INCLUDED
#define MAINMENU_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_Button.hxx>

//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport MainMenu
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    MainMenu();
    ~MainMenu();
    int Show();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the MainMenu.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
    
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group0;// Block type: Group
    NXOpen::BlockStyler::Button* button1;// Block type: Button
    NXOpen::BlockStyler::Button* button2;// Block type: Button
    NXOpen::BlockStyler::Button* button3;// Block type: Button
	NXOpen::BlockStyler::Button* button3x1;
	NXOpen::BlockStyler::Button* button3x2;
    NXOpen::BlockStyler::Button* button4;// Block type: Button
    NXOpen::BlockStyler::Button* button5;// Block type: Button
    NXOpen::BlockStyler::Button* button6;// Block type: Button
    NXOpen::BlockStyler::Button* button7;// Block type: Button
    NXOpen::BlockStyler::Button* button8;// Block type: Button
    NXOpen::BlockStyler::Button* button9;// Block type: Button
    NXOpen::BlockStyler::Button* button10;// Block type: Button
    NXOpen::BlockStyler::Button* button11;// Block type: Button
    NXOpen::BlockStyler::Button* button12;// Block type: Button
    
};
#endif //MAINMENU_H_INCLUDED
