//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\Users\Administrator\Desktop\vs\menu_block\MainMenu.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: Administrator
//              Version: NX 8.5
//              Date: 04-21-2016  (Format: mm-dd-yyyy)
//              Time: 11:23 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "MainMenu.hpp"
#include "BlockCreatePoint.hpp"
#include "BlockDrawCircle.hpp"

#include "BlockcreateRectSameX.hpp"
#include "BlockcreateRectSameY.hpp"
#include "BlockcreateRectSameZ.hpp"
#include "NXFunction.h"
#include "BlockCreateSketchOnextrude.hpp"
#include "BlockResverseExtrude.hpp"
#include "BlockCreateExtrude.hpp"

using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(MainMenu::theSession) = NULL;
UI *(MainMenu::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
MainMenu::MainMenu()
{
    try
    {
        // Initialize the NX Open C++ API environment
        MainMenu::theSession = NXOpen::Session::GetSession();
        MainMenu::theUI = UI::GetUI();
        theDlxFileName = "D:\\xietongkuangjia3\\nxcocadapp_cp1\\interface\\NXCoCadTest\\NXCoCadTest\\MainMenu.dlx";
        theDialog = MainMenu::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &MainMenu::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &MainMenu::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &MainMenu::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &MainMenu::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &MainMenu::dialogShown_cb));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
MainMenu::~MainMenu()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_ROOT_DIR\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------
/*extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
    MainMenu *theMainMenu = NULL;
    try
    {
        theMainMenu = new MainMenu();
        // The following method shows the dialog immediately
        theMainMenu->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        MainMenu::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(theMainMenu != NULL)
    {
        delete theMainMenu;
        theMainMenu = NULL;
    }
}*/

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
/*extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}*/

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
/*extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        MainMenu::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}*/

int MainMenu::Show()
{
    try
    {
        theDialog->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        MainMenu::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void MainMenu::initialize_cb()
{
    try
    {
        group0 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group0"));
        button1 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button1"));
        button2 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button2"));
        button3 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button3"));
		button3x1 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button3x1"));
		button3x2 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button3x2"));
        button4 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button4"));
        button5 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button5"));
        button6 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button6"));
        button7 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button7"));
        button8 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button8"));
        button9 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button9"));
        button10 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button10"));
        button11 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button11"));
        button12 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button12"));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        MainMenu::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void MainMenu::dialogShown_cb()
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        MainMenu::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int MainMenu::apply_cb()
{
    int errorCode = 0;
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        MainMenu::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int MainMenu::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
		//画圆
        if(block == button1)
        {
			BlockDrawCircle *theBlockDrawCircle = NULL;
        //---------Enter your code here-----------
			try
			{
				theBlockDrawCircle = new BlockDrawCircle();
				// The following method shows the dialog immediately
				theBlockDrawCircle->Show();
			}
			catch(exception& ex)
			{
				//---- Enter your exception handling code here -----
				BlockCreatePoint::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
			}
        }
		//拉伸
        else if(block == button2)
        {
        //---------Enter your code here-----------
			BlockCreateExtrude *block = NULL;
			try
			{
				block = new BlockCreateExtrude();
				block->Show();
			}
			catch(exception & e)
			{
				BlockCreatePoint::theUI->NXMessageBox()->Show("111111", NXOpen::NXMessageBox::DialogTypeError,"111111");
			}
        }
		//创建矩形 Z轴相等
        else if(block == button3)
        {
        //---------Enter your code here-----------
			BlockCreateRectSameZ *theBlcokCreateRectSameZ = NULL;
			//---------Enter your code here-----------
			try
			{
				theBlcokCreateRectSameZ = new BlockCreateRectSameZ();
				// The following method shows the dialog immediately
				theBlcokCreateRectSameZ->Show();
			}
			catch(exception& ex)
			{
				//---- Enter your exception handling code here -----
				BlockCreatePoint::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
			}
		}
		//创建矩形 Y轴相等
		else if(block == button3x1)
		{
			//---------Enter your code here-----------
			BlockCreateRectSameY *theBlcokCreateRectSameY = NULL;
			//---------Enter your code here-----------
			try
			{
				theBlcokCreateRectSameY = new BlockCreateRectSameY();
				// The following method shows the dialog immediately
				theBlcokCreateRectSameY->Show();
			}
			catch(exception& ex)
			{
				//---- Enter your exception handling code here -----
				BlockCreatePoint::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
			}
		}
		//创建矩形 X轴相等
		else if(block == button3x2)
		{
			//---------Enter your code here-----------
			BlockcreateRectSameX *theBlcokCreateRectSameX = NULL;
			//---------Enter your code here-----------
			try
			{
				theBlcokCreateRectSameX = new BlockcreateRectSameX();
				// The following method shows the dialog immediately
				theBlcokCreateRectSameX->Show();
			}
			catch(exception& ex)
			{
				//---- Enter your exception handling code here -----
				BlockCreatePoint::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
			}
		}
		//反向拉伸
        else if(block == button4)
        {
			BlockResverseExtrude *block = NULL;
			try
			{
				block = new BlockResverseExtrude();
				block->Show();
			}
			catch (exception& e)
			{
				BlockCreatePoint::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, e.what());
			}
			
        //---------Enter your code here-----------
        }
        else if(block == button5)
        {
        //---------Enter your code here-----------
        }
        else if(block == button6)
        {
        //---------Enter your code here-----------
        }
		//创建初始草图
        else if(block == button7)
        {
        //---------Enter your code here-----------
			createSketch();
        }
		//拉伸体上见草图
        else if(block == button8)
        {
        //---------Enter your code here-----------
			BlockCreateSketchOnextrude *block = NULL;
			try{
				block = new BlockCreateSketchOnextrude();
				block->Show();
			}
			catch(exception &ex)
			{
				BlockCreatePoint::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
			}
        }
        else if(block == button9)
        {
        //---------Enter your code here-----------
        }
		//建点
        else if(block == button10)
        {
        //---------Enter your code here-----------
			BlockCreatePoint *theBlockCreatePoint = NULL;
			try
			{
				theBlockCreatePoint = new BlockCreatePoint();
				// The following method shows the dialog immediately
				theBlockCreatePoint->Show();
			}
			catch(exception& ex)
			{
				//---- Enter your exception handling code here -----
				BlockCreatePoint::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
			}
        }
        else if(block == button11)
        {
        //---------Enter your code here-----------
        }
        else if(block == button12)
        {
        //---------Enter your code here-----------
        }
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        MainMenu::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int MainMenu::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        MainMenu::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* MainMenu::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}

