//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\CollaborativeFramework_20160404\nxcocadapp\NXCoCADTest.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: NicholasWang
//              Version: NX 8.5
//              Date: 04-12-2016  (Format: mm-dd-yyyy)
//              Time: 13:46
//
//==============================================================================

#ifndef NXCOCADTEST_H_INCLUDED
#define NXCOCADTEST_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------


//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport NXCoCADTest
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    NXCoCADTest();
    ~NXCoCADTest();
    int Show();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the NXCoCADTest.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group0;// Block type: Group
    NXOpen::BlockStyler::DoubleBlock* double0;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double01;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* double02;// Block type: Double
    NXOpen::BlockStyler::Button* button0;// Block type: Button
    
};

DllExport bool Initialize(void);
DllExport bool Terminate(void);

double dCoordinate[3];

#endif //NXCOCADTEST_H_INCLUDED
